export declare class StreamingAudioChannel {
    static maxChannels: number;
    static _channels: Array<StreamingAudioChannel>;
    private _sourceOpenDelegate;
    private _updateEndDelegate;
    private _sourceBuffer;
    private _sourceDirty;
    private _isPlaying;
    private _isLooping;
    private _isQueuing;
    private _isOpening;
    private _buffer;
    private _offset;
    private _volume;
    private _startTime;
    private _duration;
    private _audio;
    private _mediaSource;
    private _urlString;
    readonly duration: number;
    readonly currentTime: number;
    volume: number;
    isPlaying(): boolean;
    isLooping(): boolean;
    isDecoding(): boolean;
    constructor();
    play(buffer: ArrayBuffer, offset?: number, loop?: boolean): void;
    stop(): void;
    private _sourceOpen(event);
    private _queueBuffer();
    private _updateEnd(event);
    private _onTimeUpdate(event);
    private _updateSource();
    private _disposeSource();
}
