"use strict";
var AbstractMethodError_1 = require("./errors/AbstractMethodError");
exports.AbstractMethodError = AbstractMethodError_1.AbstractMethodError;
var ArgumentError_1 = require("./errors/ArgumentError");
exports.ArgumentError = ArgumentError_1.ArgumentError;
var DocumentError_1 = require("./errors/DocumentError");
exports.DocumentError = DocumentError_1.DocumentError;
var ErrorBase_1 = require("./errors/ErrorBase");
exports.ErrorBase = ErrorBase_1.ErrorBase;
var PartialImplementationError_1 = require("./errors/PartialImplementationError");
exports.PartialImplementationError = PartialImplementationError_1.PartialImplementationError;
var RangeError_1 = require("./errors/RangeError");
exports.RangeError = RangeError_1.RangeError;
